import { CheckCircle, AlertTriangle, Activity, Download } from 'lucide-react';

/**
 * Display prediction results with confidence scores
 * @param {Object} result - Prediction result object
 * @param {Function} onNewPrediction - Callback to start new prediction
 */
const ResultCard = ({ result, onNewPrediction }) => {
  if (!result) return null;

  const { label, confidence, probabilities = [], imageUrl } = result;

  // Determine status based on confidence
  const getStatus = () => {
    if (confidence >= 80) return { color: 'green', icon: CheckCircle, text: 'High Confidence' };
    if (confidence >= 60) return { color: 'yellow', icon: AlertTriangle, text: 'Medium Confidence' };
    return { color: 'red', icon: AlertTriangle, text: 'Low Confidence' };
  };

  const status = getStatus();
  const StatusIcon = status.icon;

  /**
   * Get color class based on confidence level
   */
  const getConfidenceColor = (conf) => {
    if (conf >= 80) return 'bg-green-500';
    if (conf >= 60) return 'bg-yellow-500';
    return 'bg-red-500';
  };

  /**
   * Download result as text file
   */
  const downloadResult = () => {
    const content = `Cotton Disease Detection Result
    
Detected Disease: ${label}
Confidence: ${confidence}%
Timestamp: ${new Date(result.timestamp).toLocaleString()}

${probabilities.length > 0 ? `
All Probabilities:
${probabilities.map(p => `- ${p.class}: ${p.probability.toFixed(2)}%`).join('\n')}
` : ''}

Generated by CottonAid - Cotton Disease Detection System
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cotton-disease-result-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="card fade-in">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold text-gray-800">Detection Result</h2>
        <div className={`flex items-center space-x-2 px-3 py-1 rounded-full bg-${status.color}-100`}>
          <StatusIcon className={`w-4 h-4 text-${status.color}-600`} />
          <span className={`text-sm font-semibold text-${status.color}-700`}>
            {status.text}
          </span>
        </div>
      </div>

      {/* Image preview */}
      {imageUrl && (
        <div className="mb-6">
          <img
            src={imageUrl}
            alt="Analyzed cotton leaf"
            className="w-full max-h-64 object-contain rounded-lg shadow-md"
          />
        </div>
      )}

      {/* Main result */}
      <div className="bg-gradient-to-r from-primary-50 to-primary-100 rounded-xl p-6 mb-6">
        <p className="text-sm font-semibold text-primary-700 mb-2">
          Detected Condition
        </p>
        <h3 className="text-3xl font-bold text-primary-900 mb-4">
          {label}
        </h3>
        
        <div className="flex items-center space-x-3">
          <Activity className="w-6 h-6 text-primary-600" />
          <div className="flex-1">
            <p className="text-sm text-primary-700 mb-1">Confidence Score</p>
            <div className="flex items-center space-x-3">
              <div className="flex-1 bg-white rounded-full h-3 overflow-hidden">
                <div
                  className={`h-full ${getConfidenceColor(confidence)} transition-all duration-500`}
                  style={{ width: `${confidence}%` }}
                />
              </div>
              <span className="text-2xl font-bold text-primary-900">
                {confidence}%
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* All probabilities */}
      {probabilities.length > 0 && (
        <div className="mb-6">
          <h4 className="text-lg font-semibold text-gray-800 mb-3">
            All Disease Probabilities
          </h4>
          <div className="space-y-3">
            {probabilities
              .sort((a, b) => b.probability - a.probability)
              .map((prob, index) => (
                <div key={index} className="space-y-1">
                  <div className="flex justify-between text-sm">
                    <span className="font-medium text-gray-700">
                      {prob.class}
                    </span>
                    <span className="text-gray-600">
                      {prob.probability.toFixed(2)}%
                    </span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2 overflow-hidden">
                    <div
                      className="bg-primary-500 h-full transition-all duration-500"
                      style={{ width: `${prob.probability}%` }}
                    />
                  </div>
                </div>
              ))}
          </div>
        </div>
      )}

      {/* Recommendations */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
        <h4 className="font-semibold text-blue-900 mb-2">
          💡 Recommendations
        </h4>
        <ul className="text-sm text-blue-800 space-y-1">
          {label.toLowerCase().includes('healthy') ? (
            <>
              <li>• Your cotton plant appears healthy</li>
              <li>• Continue regular monitoring</li>
              <li>• Maintain proper irrigation and nutrition</li>
            </>
          ) : (
            <>
              <li>• Consult with an agricultural expert</li>
              <li>• Consider appropriate treatment measures</li>
              <li>• Monitor other plants for similar symptoms</li>
              <li>• Document the progression of symptoms</li>
            </>
          )}
        </ul>
      </div>

      {/* Action buttons */}
      <div className="flex flex-col sm:flex-row gap-3">
        <button
          onClick={onNewPrediction}
          className="btn-primary flex-1 flex items-center justify-center space-x-2"
        >
          <Activity className="w-5 h-5" />
          <span>Analyze Another Image</span>
        </button>
        <button
          onClick={downloadResult}
          className="btn-secondary flex items-center justify-center space-x-2"
        >
          <Download className="w-5 h-5" />
          <span>Download Result</span>
        </button>
      </div>

      {/* Timestamp */}
      <p className="text-xs text-gray-500 text-center mt-4">
        Analysis completed at {new Date(result.timestamp).toLocaleString()}
      </p>
    </div>
  );
};

export default ResultCard;
